c
cccccccccccccccccccccccccccccc  p a r a m  ccccccccccccccccccccccccccccc
cc                                                                    cc
cc    p u r p o s e :                                                 cc
cc                                                                    cc
cc    this include file specifies the dimensions of variables used    cc
cc                                                                    cc
cc    q u a n t i t i e s :                                           cc
cc                                                                    cc
cc       kp - maximum number of vertical levels.                      cc
cc     mxth - maximum number of angular integration points            cc
cc     mxmc - maximum number of photons in monte carlo                cc
cc                                                                    cc
cc                                                                    cc
cccccccccccccccccccccccccccccc  p a r a m  ccccccccccccccccccccccccccccc
c
      integer kp, mxth, mxmc
c
      parameter (kp=140, mxth=36, mxmc=100000)